version: "3.7"

services:
  ganache:
    image: trufflesuite/ganache-cli
    command:
      - ganache-cli
      - --db=/data/ganache
      - --fork=https://node.moonnet.space/uuid/${MOONNET_UUID}
      - --hostname=0.0.0.0
    ports:
      - "8545:8545"
    volumes:
      - ganache:/data/ganache

  thegraph:
    image: graphprotocol/graph-node
    command: /bin/bash -c "
      wait-for-it.sh postgres:5432 --timeout=60 &&
      wait-for-it.sh ipfs:5001 --timeout=60 &&
      sleep 5 &&
      graph-node
      --ethereum-rpc=mainnet:http://ganache:8545
      --postgres-url=postgresql://graph-node:let-me-in@postgres:5432/graph-node
      --ipfs=ipfs:5001
      --debug"
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8020:8020"
    depends_on:
      - ipfs
      - postgres
      - ganache
    environment:
      RUST_LOG: info

  ipfs:
    image: ipfs/go-ipfs:v0.4.23
    ports:
      - "5001:5001"
    volumes:
      - ipfs:/data/ipfs

  postgres:
    image: postgres
    command: ["postgres", "-cshared_preload_libraries=pg_stat_statements"]
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: graph-node
      POSTGRES_PASSWORD: let-me-in
      POSTGRES_DB: graph-node

volumes:
  ganache:
  ipfs:
  postgres:
